name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - master
      - dev

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint --if-present

      - name: Run Tests
        run: npm test --if-present
